// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ6vm3j6U7eHgr-I2YcXZ2slH7EDOQn14',
    appId: '1:694484782416:web:327bfccd36a34e8cd43055',
    messagingSenderId: '694484782416',
    projectId: 'to-do-list-9bcc4',
    authDomain: 'to-do-list-9bcc4.firebaseapp.com',
    storageBucket: 'to-do-list-9bcc4.firebasestorage.app',
    measurementId: 'G-MYHBR9X0CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kyUD9Qm74DJzD2gOBX5yTlJQbVIiJOk',
    appId: '1:694484782416:android:0fccd0e9c644aa4ad43055',
    messagingSenderId: '694484782416',
    projectId: 'to-do-list-9bcc4',
    storageBucket: 'to-do-list-9bcc4.firebasestorage.app',
  );
}
